# GitHub sponsor button configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: klodr
patreon: klodr
ko_fi: klodr
